#!/bin/bash

docker run -it --rm -v "${PWD}:/usr/share/project" -e APP_ENV=dev -e YDL_PATH=/usr/share/project/downloads -p 80:80 -w "/usr/share/project" --entrypoint sh --name dev_crystal jmhelbig/garnet:latest
