#!/bin/bash

docker run -it --rm -v "${PWD}:/usr/share/project" -e APP_ENV=dev -e YDL_PATH=/usr/share/project/downloads -p 80:8080 -w "/usr/share/project" --entrypoint bash --name dev_crystal jmhelbig/garnet:latest
