#!/bin/bash

docker run --rm -d -v "/$HOME/Downloads:/usr/share/project/downloads" -e APP_ENV=test -e YDL_PATH=/usr/share/project/downloads -p 80:8080 -w "/usr/share/project" --name garnet_test jmhelbig/garnet:latest
